name: rong_client
description: Client for rong.
publish_to: none
version: 1.0.0
homepage: https://github.com/kinstaky/rong_client
documentation: https://kinstaky.github.io/rong_client

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  async: ^2.2.0
  grpc: ^4.0.0
  protobuf: ^3.0.0
  collection: ^1.18.0-nullsafety.4
  provider: ^6.0.0
  fl_chart: ^0.70.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  lints: ^5.1.1

  hive_generator: ^2.0.1
  build_runner: ^2.4.12

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: NotoSansSC
      fonts:
      - asset: fonts/NotoSansSC-Regular.ttf