display_name: Rong Client
package_name: rong-client

maintainer:
  name: kinstaky
  eamil: kinstaky@163.com

priority: optional
section: x11
installed_size: 24576

essential: false
generic_name: Rong Application
startup_notify: false
# icon:
# metainfo:
